function qpgen_setup(varargin)
%% Setup script for qpgen

% Parse input
opt_clb = any(strcmp(varargin, '-cuda_lib'));
opt_cbn = any(strcmp(varargin, '-cuda_bin'));

if ismac
  cuda_lib = '/usr/local/cuda/lib';
  cuda_bin = '/usr/local/cuda/bin';
elseif isunix
  cuda_lib = '/usr/local/cuda/lib64';
  cuda_bin = '/usr/local/cuda/bin';
end

if opt_clb
  idx_lib = find(strcmp(varargin, '-cuda_lib')) + 1;
  cuda_lib = varargin{idx_lib};
end

if opt_cbn
  idx_bin = find(strcmp(varargin, '-cuda_bin')) + 1;
  cuda_bin = varargin{idx_bin};
end

unix('make clean');
unix(sprintf(['export PATH=$PATH:%s;' ...
              'export DYLD_LIBRARY_PATH=%s:$DYLD_LIBRARY_PATH;' ...
              'make qpgen_ln.o'], ...
             cuda_bin, cuda_lib));
try
  fprintf('Linking to standard library failed, trying another.\n')
  eval(sprintf(['mex -largeArrayDims -I. -output qpgen_init ' ...
                'LDFLAGS=''\\$LDFLAGS -Wl,-rpath,%s'' ' ...
                'CXXFLAGS=''\\$CXXFLAGS -std=c++11'' ' ...
                'qpgen_init_mex.cpp qpgen.o qpgen_ln.o ' ...
                '-L%s -lcudart -lcublas -lcusparse '], ...
               cuda_lib, cuda_lib))
  eval(sprintf(['mex -largeArrayDims -I. -output qpgen_run ' ...
                'LDFLAGS=''\\$LDFLAGS -Wl,-rpath,%s'' ' ...
                'CXXFLAGS=''\\$CXXFLAGS -std=c++11'' ' ...
                'qpgen_run_mex.cpp qpgen.o qpgen_ln.o ' ...
                '-L%s -lcudart -lcublas -lcusparse '], ...
               cuda_lib, cuda_lib))
  eval(sprintf(['mex -largeArrayDims -I. -output qpgen_clear ' ...
                'LDFLAGS=''\\$LDFLAGS -Wl,-rpath,%s'' ' ...
                'CXXFLAGS=''\\$CXXFLAGS -std=c++11'' ' ...
                'qpgen_clear_mex.cpp qpgen.o qpgen_ln.o ' ...
                '-L%s -lcudart -lcublas -lcusparse '], ...
               cuda_lib, cuda_lib))
catch
  eval(sprintf(['mex -largeArrayDims -I.  -output qpgen_init ' ...
                'LDFLAGS=''\\$LDFLAGS -stdlib=libstdc++ -Wl,-rpath,%s'' ' ...
                'CXXFLAGS=''\\$CXXFLAGS -stdlib=libstdc++ -std=c++11'' ' ...
                'qpgen_init_mex.cpp qpgen.o qpgen_ln.o ' ...
                '-L%s -lcudart -lcublas -lcusparse '], ...
               cuda_lib, cuda_lib))
  eval(sprintf(['mex -largeArrayDims -I. -output qpgen_run ' ...
                'LDFLAGS=''\\$LDFLAGS -stdlib=libstdc++ -Wl,-rpath,%s'' ' ...
                'CXXFLAGS=''\\$CXXFLAGS -stdlib=libstdc++ -std=c++11'' ' ...
                'qpgen_run_mex.cpp qpgen.o qpgen_ln.o ' ...
                '-L%s -lcudart -lcublas -lcusparse '], ...
               cuda_lib, cuda_lib))
  eval(sprintf(['mex -largeArrayDims -I. -output qpgen_clear' ...
                'LDFLAGS=''\\$LDFLAGS -stdlib=libstdc++ -Wl,-rpath,%s'' ' ...
                'CXXFLAGS=''\\$CXXFLAGS -stdlib=libstdc++ -std=c++11'' ' ...
                'qpgen_clear_mex.cpp qpgen.o qpgen_ln.o ' ...
                '-L%s -lcudart -lcublas -lcusparse '], ...
               cuda_lib, cuda_lib))
end

fprintf('Setup Successful.\n')

